---
# 1. DEPLOYMENT CHO JUICE SHOP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  namespace: "{{k8s_namespace}}"
  labels:
    app: juice-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: juice-shop
        image: "{{app_image}}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# 2. SERVICE XUẤT PORT 80 CHO DAST SCAN
apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
  namespace: "{{k8s_namespace}}"
spec:
  type: LoadBalancer
  selector:
    app: juice-shop
  ports:
  - protocol: TCP
    port: 80 # Mở port 80 thẳng ra Internet
    targetPort: 3000 # Port thực tế của container
