# --- BỘ LUẬT 1:CHECK KEYLESS VÀ SBOM CHO NODEGOAT (KHO PRIVATE) ---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-signed-project-images
spec:
  images:
    - glob: "ghcr.io/nt524/secure-ci-cd-pipeline/nodegoat*"
  authorities:
    - keyless:
        url: https://fulcio.sigstore.dev
        identities:
          - issuer: https://token.actions.githubusercontent.com
            subjectRegExp: "https://github.com/NT524/.*"
      
      # KHỐI NÀY: Để Sigstore mượn token chui vào kho Private lấy chữ ký/SBOM
      importSecrets:
        - name: ghcr-registry-auth
      
      attestations:
        - name: check-sbom-attachment
          predicateType: https://spdx.dev/Document
          policy:
            type: rego
            data: |
              package sigstore
              default allow = false
              allow {
                # Kiểm tra dữ liệu chứng thực SBOM tồn tại
                input.predicate != null
              }

---
# --- BỘ LUẬT 2: CHO PHÉP MONGODB QUA CỬA KHÔNG CẦN KIỂM TRA ---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: allow-public-images
spec:
  images:
    - glob: "index.docker.io/library/mongo*"
    - glob: "docker.io/library/mongo*"
  authorities:
    - static:
        action: pass