apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-signed-project-images
spec:
  images:
    - glob: "ghcr.io/nt524/secure-ci-cd-pipeline/nodegoat*"
  authorities:
    - keyless:
        url: https://fulcio.sigstore.dev
        identities:
          - issuer: https://token.actions.githubusercontent.com
            # ĐỔI LẠI ĐÚNG TRƯỜNG DỮ LIỆU CHUẨN:
            subjectRegexp: "https://github.com/NT524/.*"
      
      # ĐƯA IMPORTSECRETS VÀO LỒNG BÊN TRONG KHỐI AUTHORITY NÀY:
      importSecrets:
        - name: ghcr-registry-auth

      # ĐƯA CHỐT CHẶN KIỂM TRA SBOM VÀO LỒNG BÊN TRONG AUTHORITY NÀY LUÔN:
      attestations:
        - name: check-sbom-attachment
          predicateType: spdxjson
          policy:
            type: configmap
            data:
              name: sbom-verification-policy
              namespace: cosign-system

---
# Định nghĩa luật kiểm tra định dạng dữ liệu của file SBOM đi kèm (Giữ nguyên)
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbom-verification-policy
  namespace: cosign-system
data:
  policy.rego: |
    package sigstore
    default allow = false
    allow {
      input.predicate.is_valid == true
    }