env:
  contexts:
  - name: "nodegoat-staging-context"
    urls:
<<<<<<< HEAD
    - "${TARGET_URL}" # Tự động nhận URL từ tham số target của file deploy.yml truyền sang
    includeCmds: true
    excludeCmds: []
    
    # CẤU HÌNH AUTHENTICATION: ĐĂNG NHẬP TỰ ĐỘNG VÀO NODEGOAT
=======
    - "${TARGET_URL}"
    includeCmds: true
    excludeCmds: []
    # CẤU HÌNH AUTHENTICATION (ĐĂNG NHẬP TỰ ĐỘNG VÀO NODEGOAT)
>>>>>>> feature/juice-shop
    authentication:
      method: "form"
      parameters:
        loginUrl: "${TARGET_URL}/login"
        loginRequestData: "username={%username%}&password={%password%}"
      verification:
        method: "response"
        loggedOutRegex: '.*href="/login".*'
        loggedInRegex: '.*href="/logout".*'
<<<<<<< HEAD
    
=======
>>>>>>> feature/juice-shop
    users:
    - name: "dast-test-user"
      credentials:
        username: "${TEST_USER}"
        password: "${TEST_PASSWORD}"
<<<<<<< HEAD

=======
>>>>>>> feature/juice-shop
  parameters:
    failOnError: false
    failOnWarning: false
    progressToStdout: true

jobs:
- type: passiveScan-config
  parameters:
    maxAlertsPerRule: 10
    scanOnlyInContext: true

<<<<<<< HEAD
# BƯỚC CRAWL: Tìm kiếm tất cả đường link, tính năng ẩn sau khi đăng nhập thành công
=======
>>>>>>> feature/juice-shop
- type: spider
  parameters:
    context: "nodegoat-staging-context"
    user: "dast-test-user"
<<<<<<< HEAD
    maxDuration: 5 # Giới hạn 5 phút quét để tránh bị treo pipeline máy ảo

# BƯỚC TẤN CÔNG THỬ NGHIỆM (ACTIVE SCAN): Dò lỗi Injection, XSS, Broken Auth
=======
    maxDuration: 5 # Giới hạn 5 phút quét tránh treo pipeline

# ACTIVE SCAN: Kiểm tra sâu các lỗi Injection, XSS, Broken Auth
>>>>>>> feature/juice-shop
- type: activeScan
  parameters:
    context: "nodegoat-staging-context"
    user: "dast-test-user"
<<<<<<< HEAD
    policy: "Light" 
    maxRuleDurationInMins: 2

# XUẤT BÁO CÁO FORMAT JSON ĐỂ PIPELINE LƯU TRỮ VÀ HIỂN THỊ
=======
    policy: "Light" # Sử dụng policy nhẹ nhàng để bảo đảm Non-destructive
    maxRuleDurationInMins: 2

# XUẤT BÁO CÁO FORMAT JSON ĐỂ PIPELINE PARSE DỮ LIỆU
>>>>>>> feature/juice-shop
- type: report
  parameters:
    template: "json-summary"
    reportDir: "/zap/wrk"
<<<<<<< HEAD
    reportFile: "zap-report"
=======
    reportFile: "zap-report"
>>>>>>> feature/juice-shop
