---
- name: Deploy Juice Shop Application to Amazon EKS
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Ansible sẽ nhận các biến này truyền từ GitHub Actions vào
    k8s_namespace: "{{ lookup('env', 'K8S_NAMESPACE') }}"
    app_image: "{{ lookup('env', 'IMAGE_NAME') }}"

  tasks:
  - name: Create Kubernetes Namespace using kubectl
    command: kubectl create namespace "{{ k8s_namespace }}"
    ignore_errors: true # Bỏ qua lỗi nếu namespace đã tồn tại từ trước

  - name: Render Kubernetes Manifest Template
    template:
      src: ../../k8s/juice-shop.yaml
      dest: /tmp/juice-shop-rendered.yaml
      # Bước này Ansible sẽ tự động điền các biến {{ k8s_namespace }} và {{ app_image }} vào file

  - name: Deploy Juice Shop Application using kubectl
    command: kubectl apply -f /tmp/juice-shop-rendered.yaml
