---
- name: Deploy Juice Shop Application to Amazon EKS
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Ansible sẽ nhận các biến này truyền từ GitHub Actions vào
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    k8s_namespace: "{{ lookup('env', 'K8S_NAMESPACE') }}"
    app_image: "{{ lookup('env', 'APP_IMAGE') }}"
    environment: "{{ lookup('env', 'ENVIRONMENT') }}"

  tasks:
  - name: Create Kubernetes Namespace for Juice Shop
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ k8s_namespace }}"
      # Ansible tự động đọc ~/.kube/config để kết nối

  - name: Deploy Juice Shop Application using Kubernetes Manifest
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', '../k8s/juice-shop.yaml') }}"
      # Ansible tự động đọc ~/.kube/config để kết nối
