---
- name: 🛠️ Cấu hình và Cài đặt Cụm K3s Cluster lên AWS EC2
  hosts: staging
  become: true # Chạy với quyền tối cao (sudo)
  vars:
    namespace_name: "nodegoat-staging"

  tasks:
  - name: 1. Kiểm tra và cập nhật bộ nhớ cache Apt (Ubuntu)
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: 2. Tải và cài đặt hệ thống K3s Core ngầm
    shell: "curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644"
    args:
      creates: /usr/local/bin/k3s # Chỉ chạy lệnh này nếu file k3s chưa tồn tại (Tránh cài đè rác)

  - name: 3. Cài đặt thư viện Python Kubernetes cho Ansible Module
    apt:
      name: python3-kubernetes
      state: present

  - name: 3. Chờ dịch vụ K3s API Server hoạt động ổn định
    command: "kubectl get nodes"
    register: k3s_status
    until: k3s_status.rc == 0
    retries: 10
    delay: 5

  - name: 4. Khởi tạo không gian tên (Namespace) cho Đồ án
    kubernetes.core.k8s:
      name: "{{ namespace_name }}"
      api_version: v1
      kind: Namespace
      state: present
    environment:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    ignore_errors: true # Đảm bảo không gãy pipeline nếu namespace đã có sẵn
