apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredImageSignatures
metadata:
  name: require-signed-project-images
spec:
  enforcementAction: deny
  match:
    namespaces:
      - isolated-staging 
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "ReplicaSet", "StatefulSet", "DaemonSet"]
      - apiGroups: ["batch"]
        kinds: ["Job", "CronJob"]
  parameters:
    provider: cosign-gatekeeper-provider
    
    # Chỉ bắt buộc quét chữ ký với các Image thuộc hệ thống Registry của nhóm
    # Điều này giúp các Pod hệ thống mặc định của AWS chạy bình thường mà không bị Gatekeeper chặn nhầm (False Positive)
    requiredRepositoryPrefixes:
      - "ghcr.io/nt524/secure-ci-cd-pipeline"