apiVersion: externaldata.gatekeeper.sh/v1alpha1
kind: Provider
metadata:
  name: cosign-gatekeeper-provider
spec:
  timeout: 10
  url: http://cosign-gatekeeper-provider.cosign-system:8090/validate
  insecureTLSSkipVerify: true
