# 1. Cấm chạy Privileged Containers
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata:
  name: deny-privileged-containers
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: [ "" ]
      kinds: [ "Pod" ]
    namespaces:
    - app-namespace-staging
    - app-namespace-pro
---
# 2. Bắt buộc Read-Only Filesystem
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPReadOnlyRootFilesystem
metadata:
  name: require-ro-rootfs
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: [ "" ]
      kinds: [ "Pod" ]
    namespaces:
    - app-namespace-staging
    - app-namespace-prod
  parameters:
    exemptImages:
    # Loại trừ provider của em ra nếu nó cần ghi file tạm, 
    # còn ứng dụng web chính thì bắt buộc phải tuân thủ
    - "{{ECR_REGISTRY}}/{{ ECR_REPOSITORY }}/cosign-gatekeeper-provider:latest"
---
# 3. Bắt buộc Drop Capabilities
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPCapabilities
metadata:
  name: drop-all-capabilities
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups: [ "" ]
      kinds: [ "Pod" ]
    namespaces:
    - app-namespace-staging
    - app-namespace-prod
  parameters:
    requiredDropCapabilities:
    - "ALL" # Ép buộc thu hồi toàn bộ quyền hệ thống của container
