name: 2. Build and Container Security

on:
  workflow_call:
    outputs:
      full_image_name:
        description: "The full tag of the built image"
        value: ${{ jobs.build-and-test.outputs.full_image_name }}
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string

  workflow_dispatch: 
env:
  AWS_REGION: ${{ inputs.AWS_REGION }}
  ECR_REPOSITORY: nt524
  APP_NAME: juice-shop
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
jobs:
  build-and-test:
    name: Build & Push Application
    # needs: [semgrep-scan, python-scan, javascript-scan, iac-scan]
    # if: always()
    runs-on: ubuntu-latest
    outputs:
      full_image_name: ${{ steps.prep.outputs.IMAGE_NAME }}

    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: app/NodeJS/juice-shop/package.json

      - name: Nạp AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Prepare Image Name & Environment
        id: prep
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # SỬA LỖI TRỐNG BIẾN: Nếu env.ENVIRONMENT bị rỗng từ file Mẹ, tự động fallback về 'staging' để không gãy tag
          ENVIRONMENT="${{ env.ENVIRONMENT }}"
          echo "ENV=${ENVIRONMENT}" >> $GITHUB_OUTPUT

          VERSION_TAG="${{ github.sha }}"
          IMAGE_NAME=${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.APP_NAME }}-${VERSION_TAG}-${ENVIRONMENT}

          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION_TAG}" >> $GITHUB_OUTPUT

      - name: Thiết lập Docker Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: app/NodeJS/juice-shop/
          load: true
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy Vulnerability Scanner (JSON Output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_NAME }}"
          format: "json"
          output: "trivy-report.json"
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Run security scan on deployed application
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_NAME }}"
          format: "sarif"
          output: "trivy-report.sarif"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true

      - name: Upload Trivy JSON Report as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-json-report
          path: trivy-report.json


      - name: Upload Trivy SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-report.sarif

      # - name: Upload Trivy Security Reports
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: trivy-container-reports
      #     path: |
      #       trivy-report.json
      #       trivy-report.html
      #       trivy-report.sarif

      

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}

      - name: Generate SBOM with Syft
        # install syft and using Syft to generate SBOM
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft ${{ env.IMAGE_NAME }} -o spdx-json > sbom.spdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom.spdx.json
          retention-days: 7
      
      - name: Push Cleaned Trivy Report to Grafana Loki
        if: always()
        run: |
          TIMESTAMP=$(date +%s%N)
          
          # Lọc file JSON, chỉ giữ lại thông tin cơ bản của từng lỗ hổng tìm thấy để giảm dung lượng file xuống 90%
          jq '[.Results[].Vulnerabilities[]? | {VulnerabilityID, PkgName, InstalledVersion, FixedVersion, Severity, Title}]' trivy-report.json > trivy_short.json
          
          # Tạo cấu trúc payload cho Loki
          jq -n \
            --arg ts "$TIMESTAMP" \
            --arg job "github-actions" \
            --arg scan_type "trivy-container-scan" \
            --arg img "${{ env.IMAGE_NAME }}" \
            --arg repo "${{ github.repository }}" \
            --slurpfile log trivy_short.json \
            '{"streams": [{"stream": {"job": $job, "scan_type": $scan_type, "image": $img, "repo": $repo}, "values": [[$ts, ($log[0] | @json)]]}]}' > loki_payload.json

          # Gửi file đã được rút gọn lên Loki
          curl -k -H "Content-Type: application/json" \
               -u "${{ secrets.LOKI_AUTH }}" \
               -X POST ${{ secrets.LOKI_URL }} \
               -d @loki_payload.json

      - name: Sign the published Docker image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "$COSIGN_PRIVATE_KEY" > cosign.key
          cosign sign --yes --key cosign.key ${{ env.IMAGE_NAME }}
          rm cosign.key
