name: 2. Build and Container Security

on:
  workflow_call:
    outputs:
      full_image_name:
        description: "The full tag of the built image"
        value: ${{ jobs.build-and-test.outputs.full_image_name }}
    inputs:
      AWS_REGION:
        required: true
        type: string

  workflow_dispatch: 
env:
  NODE_VERSION: 24
  AWS_REGION: ${{ inputs.AWS_REGION }}
  ECR_REPOSITORY: nt524
  APP_NAME: juice-shop
jobs:
  build-and-test:
    name: Build & Push Application
    runs-on: ubuntu-latest
    outputs:
      full_image_name: ${{ steps.prep.outputs.IMAGE_NAME }}

    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: app/package.json

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Prepare Image Name
        id: prep
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |

          VERSION_TAG="${{ github.sha }}"
          IMAGE_NAME=${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.APP_NAME }}-${VERSION_TAG}

          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION_TAG}" >> $GITHUB_OUTPUT

      - name: Thiết lập Docker Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: app/
          load: true
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy Vulnerability Scanner (JSON Output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_NAME }}"
          format: "json"
          output: "trivy-report.json"
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Run security scan on deployed application
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_NAME }}"
          format: "sarif"
          output: "trivy-report.sarif"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          exit-code: "1"

      - name: Upload Trivy JSON Report as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-json-report
          path: trivy-report.json


      - name: Upload Trivy SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-report.sarif
        
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Push Docker Image
        # if: steps.trivy-scan.outcome == 'success'
        run: |
          docker push ${{ env.IMAGE_NAME }}

      - name: Generate SBOM with Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft ${{ env.IMAGE_NAME }} -o spdx-json > sbom.spdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom.spdx.json
          retention-days: 7
      
      - name: Push Trivy Metrics to Grafana Prometheus
        if: always()
        run: |
          REPO="${{ github.repository }}"
          IMAGE="${{ steps.prep.outputs.IMAGE_NAME }}"

          if [ -f "trivy_short.json" ]; then
            NUM_VULNS=$(jq 'length' trivy_short.json)
          else
            NUM_VULNS=0
          fi

          # Chuẩn bị payload dạng Influx Line Protocol
          PAYLOAD="security_scan,repo=${REPO},image=${IMAGE},scan_type=container-scan vulnerabilities_count=${NUM_VULNS}"

          echo "Đang đẩy metric lên Grafana Prometheus: $PAYLOAD"

          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PROMETHEUS_AUTH }}" \
            -H "Content-Type: text/plain" \
            "https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/v1/push/influx/write" \
            -d "$PAYLOAD"

      - name: Sign the published Docker image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "$COSIGN_PRIVATE_KEY" > cosign.key
          cosign sign --yes --key cosign.key ${{ env.IMAGE_NAME }}
          rm cosign.key
