name: DevSecOps Integrated Pipeline

on:
  push:
    branches:
      - "staging"
      - "prod"
    paths-ignore:
      - "README.md"
      - "docs/**"

  pull_request:
    branches:
      - "staging"
      - "prod"
    types: [closed] 

  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  security-events: write
  issues: write
jobs:
  #===================================CI===================================

  Scan-Application:
    name: "Secret Scanning"
    uses: ./.github/workflows/scan-app.yml
    secrets: inherit 

  Scan-Infrastructure:
    name: "Checkov & Conftest IaC Scan"
    uses: ./.github/workflows/scan-iac.yml
    secrets: inherit

  Build:
    needs: [Scan-Application]
    if: | 
        (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch')
      # && (needs.Scan-Application.outcome == 'success' )
    with:
      AWS_REGION: us-east-1
    uses: ./.github/workflows/build.yml
    secrets: inherit 

  #===================================CD===================================
  Provision-staging:
    uses: ./.github/workflows/provision.yml
    needs: Scan-Infrastructure
    if: |
        (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' )
      # && (needs.Scan-IaC.outcome == 'success')
    with:
      ENVIRONMENT: staging
      AWS_REGION: us-east-1
    secrets: inherit

  Provision-prod:
    needs: Scan-Infrastructure
    uses: ./.github/workflows/provision.yml
    if: |
        (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch')
        && (github.base_ref == 'prod' || github.ref == 'refs/heads/prod')
      # && (needs.Scan-Infrastructure.outcome == 'success')
      
    with:
      ENVIRONMENT: prod
      AWS_REGION: us-east-1
    secrets: inherit

  Deploy-Policy-Gate:
    needs: [Provision-prod]
    uses: ./.github/workflows/policy_gate.yml
    with:
      ENVIRONMENT: prod
      AWS_REGION: us-east-1
      CLUSTER_NAME: ${{needs.Provision-prod.outputs.CLUSTER_NAME}}
      K8S_NAMESPACE: ${{needs.Provision-prod.outputs.K8S_NAMESPACE}}
    secrets: inherit

  Deploy-staging:
    needs: [Provision-staging, Build]
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: staging
      AWS_REGION: us-east-1
      CLUSTER_NAME: ${{needs.Provision-staging.outputs.CLUSTER_NAME}}
      K8S_NAMESPACE: ${{needs.Provision-staging.outputs.K8S_NAMESPACE}}
      full_image_name: ${{needs.Build.outputs.full_image_name}}
    secrets: inherit

  Dast-scan:
    needs: [Deploy-staging]
    uses: ./.github/workflows/zap.yml
    with:
      target: ${{needs.Deploy-staging.outputs.URL}}
    secrets: inherit

  Deploy-prod:
    needs: [Provision-prod, Build, Dast-scan]
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: prod
      AWS_REGION: us-east-1
      CLUSTER_NAME: ${{needs.Provision-prod.outputs.CLUSTER_NAME}}
      K8S_NAMESPACE: ${{needs.Provision-prod.outputs.K8S_NAMESPACE}}
      full_image_name: ${{needs.Build.outputs.full_image_name}}
    secrets: inherit
