name: Application Security Scanning

on:
  workflow_call:
    

jobs:
  secret-scan:
    name: TruffleHog (Secret Scanning)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog Scan (JSON Output)
        run: |
          docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest filesystem /pwd --json > trufflehog-report.json || true

      - name: Upload TruffleHog Security Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trufflehog-secret-reports
          path: |
            trufflehog-report.json

      - name: Push TruffleHog Report to Grafana Loki
        if: always()
        run: |
          TIMESTAMP=$(date +%s%N)
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"

          if [ -s "trufflehog-report.json" ]; then
            echo "Phát hiện có mã bí mật lộ lọt! Đang parse và gửi lên Loki..."
            
            # Sử dụng jq --slurpfile để đọc toàn bộ các dòng log của TruffleHog
            # LOẠI BỎ trường '.raw' để đảm bảo an toàn bảo mật cho hệ thống log
            jq -n \
              --arg ts "$TIMESTAMP" \
              --arg job "github-actions" \
              --arg scan_type "trufflehog-secret-scan" \
              --arg repo "$REPO" \
              --arg branch "$BRANCH" \
              --slurpfile findings trufflehog-report.json \
              '{
                streams: [{
                  stream: {job: $job, scan_type: $scan_type, repo: $repo, branch: $branch, status: "critical"},
                  values: ($findings | map([$ts, ({detector_name: .detector_name, decoder_name: .decoder_name, verified: .verified, source_metadata: .source_metadata} | tostring)]))
                }]
              }' > loki_payload.json
          else
            echo "Mã nguồn sạch sẽ. Gửi trạng thái Success lên Loki..."
            
            # Trường hợp không có lỗi, gửi 1 dòng log thông báo hệ thống an toàn
            jq -n \
              --arg ts "$TIMESTAMP" \
              --arg job "github-actions" \
              --arg scan_type "trufflehog-secret-scan" \
              --arg repo "$REPO" \
              --arg branch "$BRANCH" \
              '{
                streams: [{
                  stream: {job: $job, scan_type: $scan_type, repo: $repo, branch: $branch, status: "info"},
                  values: [[$ts, "Chúc mừng! Không tìm thấy thông tin nhạy cảm nào bị lộ lọt (No secrets found)."]]
                }]
              }' > loki_payload.json
          fi

          # Thực hiện POST payload lên Grafana Loki
          curl -k -H "Content-Type: application/json" \
               -u "${{ secrets.LOKI_AUTH }}" \
               -X POST ${{ secrets.LOKI_URL }} \
               -d @loki_payload.json
