name: Application Security Scanning

on:
  workflow_call:
    

jobs:
  secret-scan:
    name: TruffleHog (Secret Scanning)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog Scan (JSON Output)
        run: |
          docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest filesystem /pwd --json > trufflehog-report.json || true

      - name: Upload TruffleHog Security Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trufflehog-secret-reports
          path: |
            trufflehog-report.json

      - name: Push TruffleHog Metrics to Prometheus Pushgateway
        if: always()
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"

          if [ -s "trufflehog-report.json" ]; then
            echo "Phát hiện có mã bí mật lộ lọt!"
            NUM_SECRETS=$(jq 'length' trufflehog-report.json)
            STATUS="FAILED"
          else
            echo "Mã nguồn sạch sẽ."
            NUM_SECRETS=0
            STATUS="SUCCESS"
          fi

          # Định dạng dữ liệu theo chuẩn Prometheus Metrics
          cat <<EOF > metrics.txt
          # HELP devsecops_secrets_found_total Number of exposed secrets found by TruffleHog
          # TYPE devsecops_secrets_found_total gauge
          devsecops_secrets_found_total{repo="$REPO", branch="$BRANCH", scan_type="secret-scan", status="$STATUS"} $NUM_SECRETS
          EOF

          # Đẩy dữ liệu lên Prometheus Pushgateway
          curl -k -X POST --data-binary @metrics.txt ${{ secrets.PROMETHEUS_PUSHGATEWAY_URL }} -u "${{ secrets.PROMETHEUS_AUTH }}"
