name: "Terraform Manual Destroy"

on:
  workflow_dispatch: 

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          if [ -d "terraform" ]; then
            terraform -chdir=terraform init -upgrade -input=false \
              -backend-config="bucket=${{ secrets.S3_BUCKET }}" \
              -backend-config="key=terraform.tfstate" \
              -backend-config="region=us-east-1" \
              -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}"
          else
            terraform init -upgrade -input=false \
              -backend-config="bucket=${{ secrets.S3_BUCKET }}" \
              -backend-config="key=terraform.tfstate" \
              -backend-config="region=us-east-1" \
              -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}"
          fi

      - name: Terraform Destroy
        run: |
          if [ -d "terraform" ]; then
            terraform -chdir=terraform destroy -auto-approve \
              -var="ARN_IAM_USER=${{ secrets.ARN_IAM_USER }}"
              -lock=false
          else
            terraform destroy -auto-approve \
              -var="ARN_IAM_USER=${{ secrets.ARN_IAM_USER }}"
              -lock=false
          fi