name: "DAST: ZAP Active Scan (Juice Shop Test)"

on:
    workflow_call:
    workflow_dispatch:
    schedule:
        - cron: "0 18 * * 6"

jobs:
    dast_scan:
        name: OWASP ZAP DAST Scan
        runs-on: ubuntu-latest
        permissions:
            issues: write
            contents: read

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Chạy OWASP ZAP Full (Active) Scan
              uses: zaproxy/action-full-scan@v0.12.0
              with:
                  docker_name: "451620995044.dkr.ecr.us-east-1.amazonaws.com/nt524:juice-shop-b5bf36742a97d5ecd8e184c523eb56ef847179fc-staging"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  
                  target: "http://afd4675e2a8dd49d99b0e04a5aeaaaaf-19955265.us-east-1.elb.amazonaws.com/"
                  
                  rules_file_name: ".zap/rules.tsv" 
                  
                  issue_title: "🚨 DAST Alert: Vulnerabilities found in Juice Shop"
                  fail_action: true
                  
                  # [TIÊU CHÍ 3 & 5]: Giới hạn thời gian (-m 5) VÀ Thêm Authentication Header cho test account
                  # ZAP Replacer sẽ tự động chèn header 'Authorization: Bearer <token>' vào mọi request
                  cmd_options: >-
                    -a -m 5
                    -z "-config replacer.full_list(0).description=AuthHeader
                    -config replacer.full_list(0).enabled=true
                    -config replacer.full_list(0).matchtype=req_header
                    -config replacer.full_list(0).matchstr=Authorization
                    -config replacer.full_list(0).replacement=\"Bearer ${{ secrets.TEST_TOKEN }}\""
                  
                  artifact_name: "zap-scan-report"

            - name: Lưu trữ báo cáo (Gather Findings)
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: zap-scan-report-html
                  path: report_html.html